### ISSUE TITLE
Default ProcessMode of ClassLoader causes java.lang.SecurityException

### ISSUE THREAD

**Issue by hmf** [lefou/mill-jbake#10]
When I execute the command with the latest JBake version 2.6.7:

```bash
~/VSCodeProjects/hashnode-pubs$ ./mill -i site.jbake
```
I get a `java.lang.SecurityException` due to the use of reflection (see below). If I use version 2.6.4 the error is not quite the same, but it looks like the cause may be the same. Note that if I use the `JBakeModule.SubProcess` mode, the compilation finishes successfully. 

I am using JDK 11 on Linux. 

HTHs

<details close>
<summary>Verson 2.6.7</summary>
<br>

```
[7/7] site.jbake 
JBake v2.6.7 (2021-05-14 21:54:29[GMT+01:00]) [http://jbake.org]

17:08:44.514 INFO  org.jbake.app.Oven - Baking has started...
17:08:44.520 ERROR jbake - An unexpected error occurred: javax/script/ScriptEngineFactory
1 targets failed
site.jbake java.lang.reflect.InvocationTargetException
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.base/java.lang.reflect.Method.invoke(Method.java:566)
    de.tobiasroeser.mill.jbake.JBakeWorkerClassloaderImpl.runJbakeMain(JBakeWorkerClassloaderImpl.scala:59)
    de.tobiasroeser.mill.jbake.JBakeModule.$anonfun$jbake$2(JBakeModule.scala:93)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:380)
java.lang.SecurityException: JBake exit 2
    de.tobiasroeser.mill.jbake.JBakeWorkerClassloaderImpl$$anon$1.checkExit(JBakeWorkerClassloaderImpl.scala:49)
    java.base/java.lang.Runtime.exit(Runtime.java:114)
    java.base/java.lang.System.exit(System.java:1752)
    org.jbake.launcher.Main.main(Main.java:68)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.base/java.lang.reflect.Method.invoke(Method.java:566)
    de.tobiasroeser.mill.jbake.JBakeWorkerClassloaderImpl.runJbakeMain(JBakeWorkerClassloaderImpl.scala:59)
    de.tobiasroeser.mill.jbake.JBakeModule.$anonfun$jbake$2(JBakeModule.scala:93)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:380)
```

</details>

<details close>
<summary>Version 2.6.4</summary>
<br>

```
$ ./mill -i site.jbake
[7/7] site.jbake 
JBake v2.6.4 (2019-01-21 21:03:37PM) [http://jbake.org]

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/hmf/VSCodeProjects/hashnode-pubs/out/site/jbakeDistributionDir.dest/unpacked/jbake-2.6.4-bin/lib/groovy-2.5.5.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
17:07:52.880 INFO  org.jbake.app.Oven - Baking has started...
An unexpected error occurred: javax/script/ScriptEngineFactory
java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at com.orientechnologies.orient.core.Orient.<init>(Orient.java:79)
	at com.orientechnologies.orient.core.Orient.startUp(Orient.java:194)
	at com.orientechnologies.orient.core.Orient.instance(Orient.java:180)
	at org.jbake.app.ContentStore.shutdown(ContentStore.java:151)
	at org.jbake.app.Oven.bake(Oven.java:172)
	at org.jbake.launcher.Baker.bake(Baker.java:32)
	at org.jbake.launcher.Main.run(Main.java:97)
	at org.jbake.launcher.Main.run(Main.java:83)
	at org.jbake.launcher.Main.main(Main.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at de.tobiasroeser.mill.jbake.JBakeWorkerClassloaderImpl.runJbakeMain(JBakeWorkerClassloaderImpl.scala:59)
	at de.tobiasroeser.mill.jbake.JBakeModule.$anonfun$jbake$2(JBakeModule.scala:93)
	at mill.define.Task$TraverseCtx.evaluate(Task.scala:380)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$13(Evaluator.scala:627)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withErr(Console.scala:193)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$12(Evaluator.scala:627)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withOut(Console.scala:164)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$11(Evaluator.scala:626)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withIn(Console.scala:227)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$8(Evaluator.scala:625)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$8$adapted(Evaluator.scala:586)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at mill.eval.Evaluator.evaluateGroup(Evaluator.scala:586)
	at mill.eval.Evaluator.$anonfun$evaluateGroupCached$21(Evaluator.scala:478)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at mill.eval.Evaluator.evaluateGroupCached(Evaluator.scala:469)
	at mill.eval.Evaluator.$anonfun$sequentialEvaluate$2(Evaluator.scala:202)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
	at mill.eval.Evaluator.sequentialEvaluate(Evaluator.scala:177)
	at mill.eval.Evaluator.evaluate(Evaluator.scala:162)
	at mill.main.RunScript$.evaluateNamed(RunScript.scala:364)
	at mill.main.RunScript$.evaluate(RunScript.scala:349)
	at mill.main.RunScript$.$anonfun$evaluateTasks$1(RunScript.scala:314)
	at scala.util.Either.map(Either.scala:382)
	at mill.main.RunScript$.evaluateTasks(RunScript.scala:312)
	at mill.main.RunScript$.$anonfun$runScript$8(RunScript.scala:105)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at mill.main.RunScript$.runScript(RunScript.scala:104)
	at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:119)
	at mill.main.MainRunner.watchLoop2(MainRunner.scala:67)
	at mill.main.MainRunner.runScript(MainRunner.scala:92)
	at mill.MillMain$.main0(MillMain.scala:310)
	at mill.MillMain$.main(MillMain.scala:52)
	at mill.MillMain.main(MillMain.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at mill.main.client.IsolatedMillMainLoader.runMain(IsolatedMillMainLoader.java:58)
	at mill.main.client.MillClientMain.main(MillClientMain.java:67)
Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 58 more
1 targets failed
site.jbake java.lang.reflect.InvocationTargetException
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.base/java.lang.reflect.Method.invoke(Method.java:566)
    de.tobiasroeser.mill.jbake.JBakeWorkerClassloaderImpl.runJbakeMain(JBakeWorkerClassloaderImpl.scala:59)
    de.tobiasroeser.mill.jbake.JBakeModule.$anonfun$jbake$2(JBakeModule.scala:93)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:380)
java.lang.SecurityException: JBake exit 2
    de.tobiasroeser.mill.jbake.JBakeWorkerClassloaderImpl$$anon$1.checkExit(JBakeWorkerClassloaderImpl.scala:49)
    java.base/java.lang.Runtime.exit(Runtime.java:114)
    java.base/java.lang.System.exit(System.java:1752)
    org.jbake.launcher.Main.main(Main.java:64)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.base/java.lang.reflect.Method.invoke(Method.java:566)
    de.tobiasroeser.mill.jbake.JBakeWorkerClassloaderImpl.runJbakeMain(JBakeWorkerClassloaderImpl.scala:59)
    de.tobiasroeser.mill.jbake.JBakeModule.$anonfun$jbake$2(JBakeModule.scala:93)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:380)
```

</details>

**Comment by lefou** [comment]
Fixed by #14
